name: koel
version: 0.1.0
summary: Koel player
description: Koel player for Linux

confinement: strict
base: core22
grade: stable

slots:
  koel: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: org.koel # adjust accordingly to your app name and

environment:
  ALWAYS_USE_PULSEAUDIO: '1'

apps:
  koel:
    command: player
    command-chain: [ "snap/command-chain/alsa-launch" ]
    extensions: [gnome] # gnome includes the libraries required by flutter
    plugs:
      - network
      - network-bind
      - network-control
      - home
      - audio-playback
      - audio-record
      - network-manager
      - pulseaudio
      - alsa
    slots:
      - koel

icon: snap/gui/koel.png

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa


parts:
  koel:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
    stage-packages:
      - mpv
    after:
      - alsa-mixin
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
    stage:
      # restrict to only audio-related files - you need to ensure
      # that gtk3 is staged for yad to work correctly, to prompt
      # users to connect the alsa plug or proceed with pulseaudio.
      #
      # This helps prevent symbol conflicts in situations where
      # you're using a non-default library, such as those that the
      # gnome-3-34 extension for core18 provides.
      - etc/asound.conf
      - snap/command-chain/alsa-launch
      - usr/bin/yad*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libasound*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libdnsfile*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libFLAC*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libjack*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libpulse*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libsamplerate*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libspeex*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libvorbis*
      - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio



#  mpvfile:
#    plugin: python
#    source: https://github.com/mpv-player/mpv/archive/v0.35.0.tar.gz
#    override-build: |
#      wget https://waf.io/waf-2.0.22 -O waf
#      python3 waf configure --prefix=${SNAPCRAFT_PART_INSTALL} --enable-libmpv-shared --disable-build-date --disable-manpage-build --disable-alsa --enable-libarchive --disable-lua --disable-javascript --disable-uchardet --disable-drm --disable-dvdnav
#      python3 waf build
#      python3 waf install
#
#    build-packages:
#      - wget
#      - libass-dev
#      - libarchive-dev
#      - libavutil-dev
#      - libavcodec-dev
#      - libavformat-dev
#      - libswscale-dev
#      - libavdevice-dev
#      - libavfilter-dev
#      - libswresample-dev
#    stage-packages:
#      - libass9
#      - libarchive13
#      - libavutil56
#      - libavcodec58
#      - libavformat58
#      - libswscale5
#      - libavdevice58
#      - libavfilter7
#      - libswresample3
#      - libuchardet0
#      - libdvdnav4
#
